CREATE TABLE DESCRIPTION (
  id SERIAL,
  version INT,
  definition VARCHAR(1000),
  numero SERIAL,
  PRIMARY KEY (id)
);

CREATE TABLE POKEMON (
  numero SERIAL,
  nom_fr VARCHAR(256) NOT NULL,
  nom_en VARCHAR(256) NOT NULL,
  taille FLOAT NOT NULL,
  poids FLOAT NOT NULL,
  type1 SERIAL,
  type2 SERIAL,
  pdv INT NOT NULL,
  atq INT NOT NULL,
  def INT NOT NULL,
  atq_spe INT NOT NULL,
  def_spe INT NOT NULL,
  vit INT NOT NULL,
  PRIMARY KEY (numero)
);

CREATE TABLE TYPE (
  id SERIAL,
  nom VARCHAR(10) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE VERSION(
  id SERIAL,
  nom VARCHAR(50) NOT NULL,
  PRIMARY KEY(id)
);

ALTER TABLE POKEMON ADD FOREIGN KEY(type1) REFERENCES TYPE(id);

ALTER TABLE POKEMON ADD FOREIGN KEY(type2) REFERENCES TYPE(id);
ALTER TABLE DESCRIPTION ADD FOREIGN KEY (numero) REFERENCES POKEMON (numero);
ALTER TABLE DESCRIPTION ADD FOREIGN KEY(version) REFERENCES VERSION(id);