INSERT INTO type(nom) VALUES
    ('Normal'),
    ('Plante'),
    ('Feu'),
    ('Eau'),
    ('Electrik'),
    ('Glace'), 
    ('Combat'),
    ('Poison'),
    ('Sol'),
    ('Vol'),
    ('Psy'),
    ('Insecte'),
    ('Roche'),
    ('Spectre'),
    ('Dragon'),
    ('Ténèbres'),
    ('Acier'),
    ('Fée'),
    ('NULL');

INSERT INTO version(nom) VALUES
    ('Rouge'),
    ('Bleu'); 

INSERT INTO POKEMON(nom_fr, nom_en, taille, poids, type1, type2, pdv, atq, def, atq_spe, def_spe, vit) VALUES
('Bulbizarre', 'Bulbasaur', 0.7, 6.9, '2', '8', 45, 49, 49, 65, 65, 45),
('Herbizarre', 'Ivysaur', 1.0, 13, '2', '8', 60, 62, 63, 80, 80, 60),
('Florizarre', 'Venusaur', 2.0, 100, '2', '8', 80, 82, 83, 100, 100, 80),
('Salamèche', 'Charmander', 0.6, 8.5, '3', '19', 39, 52, 43, 60, 50, 65),
('Reptincel', 'Charmeleon', 1.1, 19, '3', '19', 58, 64, 58, 80, 65, 80),
('Dracaufeu', 'Charizard', 1.7, 90.5, '3', '10', 78, 84, 78, 109, 85, 100),
('Carapuce', 'Squirtle', 0.5, 9, '4', '19', 44, 48, 65, 50, 64, 43),
('Carabaffe', 'Wartortle', 1.0, 22.5, '4', '19', 59, 63, 80, 65, 80, 58),
('Tortank', 'Blastoise', 1.6, 85.5, '4', '19', 79, 83, 100, 85, 105, 78),
('Chenipan', 'Caterpie', 0.3, 2.9, '12', '19', 45, 30, 35, 20, 20, 45),
('Chrysacier', 'Metapod', 0.7, 9.9, '12', '19', 50, 20, 55, 25, 25, 30),
('Papillusion', 'Butterfree', 1.1, 32, '12', '10', 60, 45, 50, 90, 80, 70),
('Aspicot', 'Weedle', 0.3, 3.2, '12', '8', 40, 35, 30, 20, 20, 50),
('Coconfort', 'Kakuna', 0.6, 10, '12', '8', 45, 25, 50, 25, 25, 35),
('Dardargnan', 'Beedrill', 1.0, 29.5, '12', '8', 65, 80, 40, 45, 80, 75),
('Roucool', 'Pidgey', 0.3, 1.8, '1', '10', 40, 45, 40, 35, 35, 56),
('Roucoups', 'Pidgeotto', 1.1, 30, '1', '10', 63, 60, 55, 50, 50, 71),
('Roucarnage', 'Pidgeot', 1.5, 39.5, '1', '10', 83, 80, 75, 70, 70, 101),
('Ratata', 'Rattata', 0.3, 3.5, '1', '19', 30, 56, 35, 25, 35, 72),
('Rattatac', 'Raticate', 0.7, 18.5, '1', '19', 55, 81, 60, 50, 70, 97),
('Piafabec', 'Spearow', 0.3, 2, '1', '10', 40, 60, 30, 31, 31, 70),
('Rapasdepic', 'Fearow', 12, 38, '1', '10', 65, 90, 65, 61, 61, 100),
('Abo', 'Ekans', 2.0, 6.9, '8', '19', 35, 60, 44, 40, 54, 55),
('Arbok', 'Arbok', 3.5, 65, '8', '19', 60, 95, 69, 65, 79, 80),
('Pikachu', 'Pikachu', 0.4, 6, '5', '19', 35, 55, 40, 50, 50, 90),
('Raichu', 'Raichu', 0.8, 30, '5', '19', 60, 90, 55, 90, 80, 110),
('Sabelette', 'Sandshrew', 0.6, 12, '9', '19', 50, 75, 85, 20, 30, 40),
('Sablaireau', 'Sandslash', 1.0, 29.5, '9', '19', 75, 100, 110, 45, 55, 65), 
('Nidoran♀', 'Nidoran♀', 0.4, 7, '8', '19', 55, 47, 52, 40, 40, 41),
('Nidorina', 'Nidorina', 0.8, 20, '8', '19', 70, 62, 67, 55, 55, 56),
('Nidoqueen', 'Nidoqueen', 1.3, 60, '8', '9', 90, 82, 87, 75, 85, 76),
('Nidoran♂', 'Nidoran♂', 0.5, 9, '8', '19', 46, 57, 40, 40, 40, 50),
('Nidorino', 'Nidorino', 0.9, 19.5, '8', '19', 61, 72, 57, 55, 55, 65),
('Nidoking', 'Nidoking', 1.4, 62, '8', '9', 81, 92, 77, 85, 75, 85),
('Mélofée', 'Clefairy', 0.6, 7.5, '18', '19', 70, 45, 48, 60, 65, 35),
('Mélodelfe', 'Clefable', 1.3, 40, '18', '19', 95, 70, 73, 85, 90, 60),
('Goupix', 'Vulpix', 0.6, 9.9, '3', '19', 38, 41, 40, 50, 65, 65),
('Feunard', 'Ninetales', 1.1, 19.9, '3', '19', 73, 76, 75, 81, 100, 100),
('Rondoudou', 'Jigglypuff', 0.5, 5.5, '1', '18', 115, 45, 20, 45, 25, 20),
('Grodoudou', 'Wigglytuff', 1.0, 12, '1', '18', 140, 70, 45, 75, 50, 45),
('Nosferapti', 'Zubat', 0.8, 7.5, '8', '10', 40, 45, 35, 30, 40, 55),
('Nosferalto', 'Golbat', 1.6, 55, '8', '10', 75, 80, 70, 65, 75, 90),
('Mystherbe', 'Oddish', 0.5, 5.4, '2', '8', 45, 50, 55, 75, 65, 30),
('Ortide', 'Gloom', 0.8, 8.6, '2', '8', 60, 65, 70, 85, 75, 40),
('Rafflesia', 'Vileplume', 1.2, 18.6, '2', '8', 75, 80, 85, 100, 90, 50),
('Paras', 'Paras', 0.3, 5.4, '12', '2', 35, 70, 55, 45, 55, 25),
('Parasect', 'Parasect', 1.0, 29.5, '12', '2', 60, 95, 80, 60, 80, 30),
('Mimitoss', 'Venonat', 1.0, 30, '12', '8', 60, 55, 50, 40, 55, 45),
('Aeromite', 'Venomoth', 1.5, 12.5, '12', '8', 70, 65, 60, 90, 75, 90), 
('Taupiqueur', 'Diglett', 0.2, 0.8, '9', '19', 10, 55, 25, 35, 45, 95),
('Triopikeur', 'Dugtrio', 0.7, 33.3, '9', '19', 35, 100, 50, 50, 70, 120),
('Miaouss', 'Meowth', 0.4, 4.2, '1', '19', 40, 45, 35, 40, 40, 90),
('Persian', 'Persian', 1.0, 32, '1', '19', 65, 70, 60, 65, 65, 115), 
('Psykokwak', 'Psyduck', 0.8, 19.6, '4', '19', 50, 52, 48, 65, 50, 55),
('Akwakwak', 'Golduck', 1.7, 76.6, '4', '19', 80, 82, 78, 95, 80, 85),
('Férosinge', 'Mankey', 0.5, 28, '7', '19', 40, 80, 35, 35, 45, 70),
('Colosinge', 'Primeape', 1.0, 32, '7', '19', 65, 105, 60, 60, 70, 95);


INSERT INTO DESCRIPTION(version, definition, numero) VALUES
(1, 'Quand il est jeune, il absorbe les nutriments conservés dans son dos pour grandir et se développer.', 1),
(2, 'Il y a une graine sur son dos depuis sa naissance. Elle grossit un peu chaque jour.', 1),
(1, 'La lumière du soleil le rend plus fort et vigoureux. Le bulbe sur son dos grossit en conséquence.', 2),
(2, 'Son bulbe dorsal est devenu si gros qu`il ne peut plus se tenir sur ses pattes postérieures.', 2),
(1, 'Une douce senteur émane de sa plante. Cette fragrance calme tous ceux qui sont engagés dans un combat.', 3),
(2, 'Sa plante donne une grosse fleur quand elle absorbe les rayons du soleil. Il est toujours à la recherche des endroits les plus ensoleillés.', 3),
(1, 'Depuis sa naissance, une petite flamme brûle au bout de sa queue. Si cette flamme s`éteint, la vie de ce Pokémon s`éteindra elle aussi.', 4),
(2, 'Il préfère ce qui est chaud. En cas de pluie, de la vapeur se forme autour de sa queue.', 4),
(1, 'S`il s`excite pendant un combat, il crache de grandes flammes, brûlant tout ce qui se trouve aux alentours.', 5),
(2, 'Il est très brutal. En combat, il se sert de ses griffes acérées et de sa queue enflammée pour mettre en pièces ses adversaires.', 5),
(1, 'Ses ailes lui permettent de voler à plus de 1 400 m d`altitude. Ce Pokémon crache du feu à des températures très élevées.', 6),
(2, 'Son souffle brûlant peut faire fondre la roche. Il est parfois la cause d`incendies de forêt.', 6),
(1, 'S`il se sent menacé, il rétracte ses pattes dans sa carapace pour se protéger et crache de l`eau.', 7),
(2, 'Quand il rentre son cou dans sa carapace, il peut projeter de l`eau à haute pression.', 7),
(1, 'Il se sert habilement de sa queue et de ses oreilles touffues pour garder son équilibre sous l`eau.', 8),
(2, 'Il est considéré comme un symbole de longévité. On reconnaît les spécimens les plus âgés à la mousse qui pousse sur leur carapace.', 8),
(1, 'Les canons sur sa carapace tirent des jets d`eau capables de percer même de l`acier trempé.', 9),
(2, 'Il écrase ses adversaires de tout son poids pour leur faire perdre connaissance. Il rentre dans sa carapace s`il se sent en danger.', 9),
(1, 'Ses petites pattes munies de ventouses lui permettent de monter les pentes et de grimper aux murs sans se fatiguer.', 10),
(2, 'Pour se protéger, il émet par ses antennes une odeur nauséabonde qui fait fuir ses ennemis.', 10),
(1, 'Bien que son corps soit entouré d`une carapace solide, l`intérieur est si mou qu`il ne résisterait pas à une attaque violente.', 11),
(2, 'En attendant sa prochaine évolution, il ne peut que durcir sa carapace et rester immobile pour éviter de se faire attaquer.', 11),
(1, 'Il ramasse du nectar chaque jour et l`agglutine sur les poils de ses pattes pour le transporter jusqu`à son nid.', 12),
(2, 'En combat, il bat des ailes très rapidement pour projeter de la poudre toxique sur ses ennemis.', 12),
(1, 'L`aiguillon sur son front est très pointu. Il se cache dans les bois et les hautes herbes, où il se gave de feuilles.', 13),
(2, 'L`aiguillon sur son front est très pointu. Il se cache dans les bois et les hautes herbes, où il se gave de feuilles.', 13),
(1, 'Il peut à peine bouger. Quand il est menacé, il sort parfois son aiguillon pour empoisonner ses ennemis.', 14),
(2, 'l peut à peine bouger. Quand il est menacé, il sort parfois son aiguillon pour empoisonner ses ennemis.', 14),
(1, 'Il se sert de ses trois aiguillons empoisonnés situés sur les pattes avant et l`abdomen pour attaquer sans relâche ses adversaires.', 15),
(2, 'Il se sert de ses trois aiguillons empoisonnés situés sur les pattes avant et l`abdomen pour attaquer sans relâche ses adversaires.', 15),
(1, 'De nature très docile, il préfère projeter du sable pour se défendre plutôt que contre-attaquer.', 16),
(2, 'De nature très docile, il préfère projeter du sable pour se défendre plutôt que contre-attaquer.', 16),
(1, 'Ce Pokémon est très endurant. Il survole en permanence son territoire pour chasser.', 17),
(2, 'Ce Pokémon est très endurant. Il survole en permanence son territoire pour chasser.', 17),
(1, 'Ce Pokémon vole à Mach 2 quand il chasse. Ses grandes serres sont des armes redoutables.', 18),
(2, 'Ce Pokémon vole à Mach 2 quand il chasse. Ses grandes serres sont des armes redoutables.', 18),
(1, 'Il peut ronger n`importe quoi avec ses deux dents. Quand on en voit un, il y en a certainement 40 dans le coin.', 19),
(2, 'Il peut ronger n`importe quoi avec ses deux dents. Quand on en voit un, il y en a certainement 40 dans le coin.', 19),
(1, 'Ses pattes arrière sont palmées. Il peut donc poursuivre sa proie dans les cours d`eau et les rivières.', 20),
(2, 'Ses pattes arrière sont palmées. Il peut donc poursuivre sa proie dans les cours d`eau et les rivières.', 20),
(1, 'Il est incapable de voler à haute altitude. Il se déplace très vite pour protéger son territoire.', 21),
(2, 'Il est incapable de voler à haute altitude. Il se déplace très vite pour protéger son territoire.', 21),
(1, 'Un Pokémon très ancien. S`il perçoit un danger, il fuit instantanément à haute altitude.', 22),
(2, 'Un Pokémon très ancien. S`il perçoit un danger, il fuit instantanément à haute altitude.', 22),
(1, 'Plus il est âgé, plus son corps est long. La nuit, il s`enroule autour de branches d`arbres pour se reposer.', 23),
(2, 'Plus il est âgé, plus son corps est long. La nuit, il s`enroule autour de branches d`arbres pour se reposer.', 23),
(1, 'Des études ont révélé que les marques effrayantes de son corps pouvaient former six motifs différents.', 24),
(2, 'Des études ont révélé que les marques effrayantes de son corps pouvaient former six motifs différents.', 24),
(2, 'Quand plusieurs de ces Pokémon se réunissent, ils provoquent de gigantesques orages.', 25),
(1, 'Quand il s`énerve, il libère instantanément l`énergie emmagasinée dans les poches de ses joues.', 25),
(1, 'Ses oreilles se dressent lorsque les poches d`électricité sur ses joues sont chargées.', 26),
(2, 'Il se protège des décharges grâce à sa queue, qui dissipe l`électricité dans le sol.', 26),
(1, 'Il creuse le sol pour construire sa tanière. Rien n`arrête ses griffes acérées, pas même la roche la plus solide.', 27),
(2, 'Il aime se rouler dans le sable des zones désertiques pour se débarrasser des traces de terre et d`humidité qui lui collent à la peau.', 27),
(1,'Il grimpe aux arbres grâce à ses griffes acérées et fait tomber des Baies pour les Sabelette qui attendent au sol.', 28),
(2, 'Plus son habitat est sec, plus ses épines dorsales deviennent dures et lisses.', 28),
(1, 'Ce Pokémon se nourrit de Baies en les ouvrant avec ses incisives. Le bout de sa corne est plus arrondi que celui du mâle.', 29),
(2, 'Son odorat est plus développé que celui du mâle. Quand Nidoran♀ cherche à manger, il reste dans le sens du vent, qu`il détecte avec ses vibrisses.', 29),
(1, 'Si un danger menace le groupe, ces Pokémon se réunissent et l`affrontent en émettant des ultrasons en chœur.', 30),
(2, 'On pense que sa corne frontale s`est atrophiée pour lui permettre de nourrir ses petits sans les blesser.', 30),
(1, 'Ce Pokémon calme les petits de son espèce en les plaçant entre ses épines dorsales. Dans ce cas, elles ne libèrent pas de poison.', 31),
(2, 'Il est plus doué pour se défendre que pour attaquer. Grâce à son blindage d`écailles, il protège ses petits de toute agression.', 31),
(1, 'Malgré sa petite taille, il est très téméraire. Afin de protéger sa compagne, il est prêt à se battre et à risquer sa vie.', 32),
(2, 'Sa corne frontale contient un puissant poison. Les grandes oreilles de ce Pokémon très prudent sont constamment dressées.', 32),
(1, 'D`un naturel nerveux, il est prompt à se battre. Lorsqu`il a une montée d`adrénaline, la concentration de son poison augmente.', 33),
(2, 'Il erre à la recherche d`une Pierre Lune, brisant tous les rochers sur son passage avec sa corne plus solide qu`un diamant.', 33),
(1, 'Très fier de sa force, il se bat vigoureusement à l`aide de sa queue robuste et de sa corne capable de briser le diamant.', 34),
(2, 'Lorsqu`il s`énerve, il devient incontrôlable, mais il retrouve son calme face à Nidoqueen, sa compagne de longue date.', 34),
(1, 'Son comportement et son cri adorables font de lui un Pokémon très populaire. Malheureusement, il est difficile d`en croiser un spécimen.', 35),
(2, 'On dit que ceux qui voient danser un groupe de Mélofée sous la pleine lune connaîtront un grand bonheur.', 35),
(1, 'Capable d`entendre une aiguille tomber à plus d`un kilomètre, ce Pokémon préfère les endroits calmes et isolés.', 36),
(2, 'Ce Pokémon s`apparente à une petite fée qui n`apparaît que rarement devant les humains. Il court se cacher dès qu`il ressent une présence.', 36),
(1, 'Avec l`âge, la fourrure de ses six queues devient de plus en plus belle et soyeuse. Elle est chaude au toucher.', 37),
(2, 'Quand il est jeune, ce Pokémon a six queues magnifiques. De nouvelles queues apparaissent tout au long de sa croissance.', 37),
(1, 'Il est très intelligent et rancunier. Quiconque attrape une de ses queues se fera maudire pour 1 000 ans.', 38),
(2, 'On dit qu`il vit 1 000 ans et que chacune de ses queues a un pouvoir magique.', 38),
(1, 'Lorsqu`il se gonfle, il peut chanter une longue berceuse qui endort inévitablement quiconque l`entend.', 39),
(2, 'Quand ses grands yeux luisent, il chante une berceuse mystérieuse et agréable qui pousse ses ennemis à s`endormir.', 39),
(1, 'Sa fourrure est si douce et soyeuse que si on la caresse, on ne veut ni ne peut s`arrêter.', 40),
(2, 'Il a une très belle fourrure. Mieux vaut éviter de le mettre en colère, ou il gonflera avant d`attaquer de tout son corps.', 40),
(1, 'Ils vivent dans les grottes où la lumière du jour ne perce jamais. Le matin, ils se blottissent les uns contre les autres pour se réchauffer et dormir.', 41),
(2, 'Il sonde les environs en émettant des ultrasons avec sa bouche, et peut ainsi se frayer un chemin même dans les grottes les plus étroites.', 41),
(1, 'Il se déplace habilement sur ses petites pattes, s`approche silencieusement de sa proie endormie, et lui suce le sang à l’aide de ses crocs.', 42),
(2, 'Le sang des êtres vivants est son péché mignon. On dit qu`il partage parfois ce précieux breuvage avec ses congénères affamés.', 42),
(1, 'Pendant la journée, il reste en sous-sol et évite le soleil. Il grandit en se baignant au clair de lune.', 43), 
(2, 'Il ne bouge que lorsqu`il est exposé aux rayons de la lune. Il se déplace alors pour disséminer ses graines.', 43),
(1, 'Ce qui semble être sa bave est en fait du nectar très collant. Si on le touche, il est très difficile de s`en dépêtrer.', 44),
(2, 'Ses pistils sécrètent une odeur incroyablement fétide qui fait perdre connaissance à ses adversaires jusqu`à 2 km à la ronde.', 44),
(1, 'Plus ses pétales sont grands, plus il produit de pollen toxique. Toutefois, le poids de sa tête le fatigue.', 45),
(2, 'Il possède les plus gros pétales au monde, qui sèment d`épais nuages de pollen toxique à chacun de ses pas.', 45),
(1, 'Il s`enfouit pour ronger des racines, mais ce sont les champignons sur son dos qui absorbent presque tous les nutriments.', 46),
(2, 'Il s`enfouit pour ronger des racines, mais ce sont les champignons sur son dos qui absorbent presque tous les nutriments.', 46),
(1, 'À force de voir son énergie aspirée, il semblerait que ce ne soit plus l`insecte qui réfléchisse, mais le champignon sur son dos.', 47),
(2, 'À force de voir son énergie aspirée, il semblerait que ce ne soit plus l`insecte qui réfléchisse, mais le champignon sur son dos.', 47),
(1, 'Ses yeux fonctionnent comme des radars et lui permettent de voir dans l`obscurité. Ils peuvent également envoyer des rayons très puissants.', 48),
(2, 'Son corps sécrète un poison redoutable. La nuit, il capture de petits Pokémon Insecte attirés par la lumière.', 48),
(1, 'Ses yeux fonctionnent comme des radars et lui permettent de voir dans l`obscurité. Ils peuvent également envoyer des rayons très puissants.', 48),
(1, 'Il bat des ailes violemment pour projeter de la poudre empoisonnée vers ses adversaires.', 49),
(2, 'Ses ailes sont couvertes d`écailles poudreuses. À chaque battement d`ailes, il laisse tomber de la poudre hautement toxique.', 49),
(1, 'Son épiderme est très fin. S`il est exposé au soleil, son sang se réchauffe, ce qui l`affaiblit.', 50),
(2, 'Ce Pokémon vit un mètre sous terre et se nourrit de racines. Il apparaît parfois à la surface.', 50),
(1, 'En combat, il s`enfouit sous terre pour pouvoir frapper ses adversaires par surprise depuis n`importe quelle direction.', 51), 
(2, 'Ses trois têtes pilonnent le sol pour le rendre friable et ainsi faciliter l`excavation.', 51),
(1, 'Il est fasciné par les objets brillants. Lorsqu`il en voit un, la pièce sur son front se met à luire.', 52),
(2, 'Il passe ses journées à dormir. La nuit venue, il patrouille sur son territoire, les yeux brillants.', 52),
(1, 'Ce Pokémon a un comportement féroce. S`il lève la queue, cela signifie qu`il s`apprête à mordre.', 53),
(2, 'Sa magnifique fourrure suscite l`admiration, mais il est difficile à apprivoiser en raison de son caractère rétif.', 53),
(1, 'Quand son éternelle migraine devient trop forte, il manifeste d`étranges pouvoirs, mais il ne semble jamais s`en souvenir par la suite.', 54),
(2, 'Ce Pokémon a tout le temps la migraine. Quand la douleur devient trop intense, il se met à utiliser des pouvoirs mystérieux', 54),
(2, 'Quand il nage à vitesse maximale grâce à ses pattes palmées, son front se met à luire pour une raison inconnue.', 55),
(2, 'Il vit en groupe au sommet des arbres. S`il perd ses congénères de vue, la solitude le rend furieux.', 56), 
(1, 'Selon certaines recherches scientifiques, les Colossinge continuent de bouillonner de fureur même à l`intérieur d`une Poké Ball.', 57),
(2, 'Il devient fou furieux s`il se sent observé et pourchasse tout être qui croise son regard.', 57);