INSERT INTO type(nom) VALUES
    ('Normal'),
    ('Plante'),
    ('Feu'),
    ('Eau'),
    ('Electrik'),
    ('Glace'), 
    ('Combat'),
    ('Poison'),
    ('Sol'),
    ('Vol'),
    ('Psy'),
    ('Insecte'),
    ('Roche'),
    ('Spectre'),
    ('Dragon'),
    ('Ténèbres'),
    ('Acier'),
    ('Fée'),
    ('NULL');

INSERT INTO POKEMON(nom_fr, nom_en, taille, poids, type1, type2, pdv, atq, def, atq_spe, def_spe, vit) VALUES
('Bulbizarre', 'Bulbasaur', 0.7, 6.9, '2', '8', 45, 49, 49, 65, 65, 45),
('Herbizarre', 'Ivysaur', 1.0, 13, '2', '8', 60, 62, 63, 80, 80, 60),
('Florizarre', 'Venusaur', 2.0, 100, '2', '8', 80, 82, 83, 100, 100, 80),
('Salamèche', 'Charmander', 0.6, 8.5, '3', '19', 39, 52, 43, 60, 50, 65),
('Reptincel', 'Charmeleon', 1.1, 19, '3', '19', 58, 64, 58, 80, 65, 80),
('Dracaufeu', 'Charizard', 1.7, 90.5, '3', '10', 78, 84, 78, 109, 85, 100),
('Carapuce', 'Squirtle', 0.5, 9, '4', '19', 44, 48, 65, 50, 64, 43),
('Carabaffe', 'Wartortle', 1.0, 22.5, '4', '19', 59, 63, 80, 65, 80, 58),
('Tortank', 'Blastoise', 1.6, 85.5, '4', '19', 79, 83, 100, 85, 105, 78),
('Chenipan', 'Caterpie', 0.3, 2.9, '12', '19', 45, 30, 35, 20, 20, 45),
('Chrysacier', 'Metapod', 0.7, 9.9, '12', '19', 50, 20, 55, 25, 25, 30),
('Papillusion', 'Butterfree', 1.1, 32, '12', '10', 60, 45, 50, 90, 80, 70),
('Aspicot', 'Weedle', 0.3, 3.2, '12', '8', 40, 35, 30, 20, 20, 50),
('Coconfort', 'Kakuna', 0.6, 10, '12', '8', 45, 25, 50, 25, 25, 35),
('Dardargnan', 'Beedrill', 1.0, 29.5, '12', '8', 65, 80, 40, 45, 80, 75),
('Roucool', 'Pidgey', 0.3, 1.8, '1', '10', 40, 45, 40, 35, 35, 56),
('Roucoups', 'Pidgeotto', 1.1, 30, '1', '10', 63, 60, 55, 50, 50, 71),
('Roucarnage', 'Pidgeot', 1.5, 39.5, '1', '10', 83, 80, 75, 70, 70, 101),
('Ratata', 'Rattata', 0.3, 3.5, '1', '19', 30, 56, 35, 25, 35, 72),
('Rattatac', 'Raticate', 0.7, 18.5, '1', '19', 55, 81, 60, 50, 70, 97),
('Piafabec', 'Spearow', 0.3, 2, '1', '10', 40, 60, 30, 31, 31, 70),
('Rapasdepic', 'Fearow', 12, 38, '1', '10', 65, 90, 65, 61, 61, 100),
('Abo', 'Ekans', 2.0, 6.9, '8', '19', 35, 60, 44, 40, 54, 55),
('Arbok', 'Arbok', 3.5, 65, '8', '19', 60, 95, 69, 65, 79, 80),
('Pikachu', 'Pikachu', 0.4, 6, '5', '19', 35, 55, 40, 50, 50, 90),
('Raichu', 'Raichu', 0.8, 30, '5', '19', 60, 90, 55, 90, 80, 110);


INSERT INTO DESCRIPTION(version, definition, numero) VALUES
('Rouge', 'Quand il est jeune, il absorbe les nutriments conservés dans son dos pour grandir et se développer.', 1),
('Bleu', 'Il y a une graine sur son dos depuis sa naissance. Elle grossit un peu chaque jour.', 1),
('Diamant Etincelant et Perle Scintillante', 'Au début de sa vie, la graine sur son dos lui fournit les nutriments dont il a besoin pour grandir.', 1),
('Rouge', 'La lumière du soleil le rend plus fort et vigoureux. Le bulbe sur son dos grossit en conséquence.', 2),
('Bleu', 'Son bulbe dorsal est devenu si gros qu`il ne peut plus se tenir sur ses pattes postérieures.', 2),
('Diamant Etincelant et Perle Scintillante', 'Lorsque le bourgeon sur son dos gonfle, il dégage un doux parfum : c`est le signe que sa grande fleur va bientôt éclore.', 2),
('Rouge', 'Une douce senteur émane de sa plante. Cette fragrance calme tous ceux qui sont engagés dans un combat.', 3),
('Bleu', 'Sa plante donne une grosse fleur quand elle absorbe les rayons du soleil. Il est toujours à la recherche des endroits les plus ensoleillés.', 3),
('Diamant Etincelant et Perle Scintilante', 'Le parfum de sa fleur est plus fort après une journée pluvieuse, ce qui appâte les autres Pokémon.', 3),
('Rouge', 'Depuis sa naissance, une petite flamme brûle au bout de sa queue. Si cette flamme s`éteint, la vie de ce Pokémon s`éteindra elle aussi.', 4),
('Bleu', 'Il préfère ce qui est chaud. En cas de pluie, de la vapeur se forme autour de sa queue.', 4),
('Diamant Etincelant et Perle Scintillante', 'La flamme au bout de sa queue symbolise sa vitalité. Elle brûle intensément quand il est en bonne santé.', 4),
('Rouge', 'S`il s`excite pendant un combat, il crache de grandes flammes, brûlant tout ce qui se trouve aux alentours.', 5),
('Bleu', 'Il est très brutal. En combat, il se sert de ses griffes acérées et de sa queue enflammée pour mettre en pièces ses adversaires.', 5),
('Diamant Etincelant et Perle Scintillante', 'La nuit, si on observe les montagnes rocheuses où vivent les Reptincel, on aperçoit leurs queues enflammées qui brillent comme des étoiles.', 5),
('Rouge', 'Ses ailes lui permettent de voler à plus de 1 400 m d`altitude. Ce Pokémon crache du feu à des températures très élevées.', 6),
('Bleu', 'Son souffle brûlant peut faire fondre la roche. Il est parfois la cause d`incendies de forêt.', 6),
('Diamant Etincelant et Perle Scintillante', 'On raconte que plus un Dracaufeu a vécu de combats difficiles, plus sa flamme est brûlante.', 6),
('Rouge', 'S`il se sent menacé, il rétracte ses pattes dans sa carapace pour se protéger et crache de l`eau.', 7),
('Bleu', 'Quand il rentre son cou dans sa carapace, il peut projeter de l`eau à haute pression.', 7),
('Diamant Etincelant et Perle Scintillante', 'Il se réfugie dans sa carapace pour se protéger et réplique en projetant de l`eau sur ses ennemis dès que ces derniers baissent leur garde.', 7),
('Rouge', 'Il se sert habilement de sa queue et de ses oreilles touffues pour garder son équilibre sous l`eau.', 8),
('Bleu', 'Il est considéré comme un symbole de longévité. On reconnaît les spécimens les plus âgés à la mousse qui pousse sur leur carapace.', 8),
('Diamant Etincelant et Perle Scintillante', 'On dit que ce Pokémon peut atteindre l`âge de 10 000 ans. Sa queue duveteuse est un symbole de longévité populaire.', 8),
('Rouge', 'Les canons sur sa carapace tirent des jets d`eau capables de percer même de l`acier trempé.', 9),
('Bleu', 'Il écrase ses adversaires de tout son poids pour leur faire perdre connaissance. Il rentre dans sa carapace s`il se sent en danger.', 9),
('Diamant Etincelent et Perle Scintillante', 'Les jets d`eau propulsés par les canons de sa carapace sont si puissants qu`ils peuvent percer d`épaisses plaques de métal instantanément.', 9),
('Rouge', 'Ses petites pattes munies de ventouses lui permettent de monter les pentes et de grimper aux murs sans se fatiguer.', 10),
('Bleu', 'Pour se protéger, il émet par ses antennes une odeur nauséabonde qui fait fuir ses ennemis.', 10),
('Diamant Etincelant et Perle Scintillante', 'Ses antennes rouges libèrent une puanteur qui repousse ses ennemis. Il grandit un peu plus à chaque mue.', 10),
('Rouge', 'Bien que son corps soit entouré d`une carapace solide, l`intérieur est si mou qu`il ne résisterait pas à une attaque violente.', 11),
('Bleu', 'En attendant sa prochaine évolution, il ne peut que durcir sa carapace et rester immobile pour éviter de se faire attaquer.', 11),
('Diamant Etincelant et Perle Scintillante', 'Une carapace dure comme l`acier protège son corps mou. Ce Pokémon encaisse patiemment les coups en attendant d`évoluer.', 11),
('Rouge', 'Il ramasse du nectar chaque jour et l`agglutine sur les poils de ses pattes pour le transporter jusqu`à son nid.', 12),
('Bleu', 'En combat, il bat des ailes très rapidement pour projeter de la poudre toxique sur ses ennemis.', 12),
('Diamant Etincelant et Perle Scintillante', 'Ce Pokémon raffole du nectar des fleurs. Il est capable de dénicher des champs fleuris même s`ils n`ont qu`une quantité infime de pollen.', 12),
('Rouge', 'L`aiguillon sur son front est très pointu. Il se cache dans les bois et les hautes herbes, où il se gave de feuilles.', 13),
('Bleu', 'L`aiguillon sur son front est très pointu. Il se cache dans les bois et les hautes herbes, où il se gave de feuilles.', 13),
('Diamant Etincelant et Perle Scintillante', 'Il mange chaque jour l`équivalent de son poids en feuilles et il utilise l`aiguillon sur sa tête pour repousser les attaques de ses ennemis.', 13),
('Rouge', 'Il peut à peine bouger. Quand il est menacé, il sort parfois son aiguillon pour empoisonner ses ennemis.', 14),
('Bleu', 'l peut à peine bouger. Quand il est menacé, il sort parfois son aiguillon pour empoisonner ses ennemis.', 14),
('Diamant Etincelant et Perle Scintillante', 'En attendant d`évoluer, il se cache sous les feuilles et dans les creux des branchages pour échapper à la vigilance des prédateurs.', 14),
('Rouge', 'Il se sert de ses trois aiguillons empoisonnés situés sur les pattes avant et l`abdomen pour attaquer sans relâche ses adversaires.', 15),
('Bleu', 'Il se sert de ses trois aiguillons empoisonnés situés sur les pattes avant et l`abdomen pour attaquer sans relâche ses adversaires.', 15),
('Diamant Etincelant et Perle Scintillante', 'Sa meilleure tactique consiste à virevolter rapidement autour de sa cible et à la piquer avec ses dards empoisonnés avant de s`enfuir.', 15),
('Rouge', 'De nature très docile, il préfère projeter du sable pour se défendre plutôt que contre-attaquer.', 16),
('Bleu', 'De nature très docile, il préfère projeter du sable pour se défendre plutôt que contre-attaquer.', 16),
('Diamant Etincelant et Perle Scintillante', 'Ce Pokémon docile préfère éviter le combat. Toutefois, il se montre très féroce quand on l`agresse.', 16),
('Rouge', 'Ce Pokémon est très endurant. Il survole en permanence son territoire pour chasser.', 17),
('Bleu', 'Ce Pokémon est très endurant. Il survole en permanence son territoire pour chasser.', 17),
('Diamant Etincelant et Perle Scintillante', 'Il survole son vaste territoire en quête de proies, avant de fondre sur elles et de les achever à l`aide des serres de ses longues pattes.', 17),
('Rouge', 'Ce Pokémon vole à Mach 2 quand il chasse. Ses grandes serres sont des armes redoutables.', 18),
('Bleu', 'Ce Pokémon vole à Mach 2 quand il chasse. Ses grandes serres sont des armes redoutables.', 18),
('Diamant Etincelant et Perle Scintillante', 'En battant des ailes de toutes ses forces, Roucarnage génère des rafales capables de faire fléchir même les plus grands arbres.', 18),
('Rouge', 'Il peut ronger n`importe quoi avec ses deux dents. Quand on en voit un, il y en a certainement 40 dans le coin.', 19),
('Bleu', 'Il peut ronger n`importe quoi avec ses deux dents. Quand on en voit un, il y en a certainement 40 dans le coin.', 19),
('Diamant Etincelant et Perle Scintillante', 'Ce Pokémon extrêmement prudent possède une vitalité à toute épreuve qui lui permet de vivre dans n`importe quel type d`habitat.', 19),
('Rouge', 'Ses pattes arrière sont palmées. Il peut donc poursuivre sa proie dans les cours d`eau et les rivières.', 20),
('Bleu', 'Ses pattes arrière sont palmées. Il peut donc poursuivre sa proie dans les cours d`eau et les rivières.', 20),
('Diamant Etincelant et Perle Scintillante', 'Il fait ses dents sur des matériaux durs, car ses incisives n`arrêtent pas de pousser. Avec celles-ci, il est capable de détruire un mur de parpaings.', 20),
('Rouge', 'Il est incapable de voler à haute altitude. Il se déplace très vite pour protéger son territoire.', 21),
('Bleu', 'Il est incapable de voler à haute altitude. Il se déplace très vite pour protéger son territoire.', 21),
('Diamant Etincelant et Perle Scintillante', 'Il vole en battant vigoureusement de ses petites ailes et trouve ses proies dans les hautes herbes à l`aide de son bec.', 21),
('Rouge', 'Un Pokémon très ancien. S`il perçoit un danger, il fuit instantanément à haute altitude.', 22),
('Bleu', 'Un Pokémon très ancien. S`il perçoit un danger, il fuit instantanément à haute altitude.', 22),
('Diamant Etincelant et Perle Scintillante', 'Très endurant, il est capable de voler toute la journée grâce à ses grandes ailes. En combat, il frappe ses ennemis à l`aide de son bec acéré.', 22),
('Rouge', 'Plus il est âgé, plus son corps est long. La nuit, il s`enroule autour de branches d`arbres pour se reposer.', 23),
('Bleu', 'Plus il est âgé, plus son corps est long. La nuit, il s`enroule autour de branches d`arbres pour se reposer.', 23),
('Diamant Etincelant et Perle Scintillante', 'Il se faufile dans l`herbe sans un bruit et attaque sa proie par-derrière quand elle s`y attend le moins.', 23),
('Bleu', 'Des études ont révélé que les marques effrayantes de son corps pouvaient former six motifs différents.', 24),
('Rouge', 'Des études ont révélé que les marques effrayantes de son corps pouvaient former six motifs différents.', 24),
('Diamant Etincelant et Perle Scintillante', 'Le motif sur son corps lui permet d`intimider ses ennemis. Une fois qu`ils sont pétrifiés de peur, il s`enroule autour d`eux pour les étouffer.', 24),
('Bleu', 'Quand plusieurs de ces Pokémon se réunissent, ils provoquent de gigantesques orages.', 25),
('Rouge', 'Quand il s`énerve, il libère instantanément l`énergie emmagasinée dans les poches de ses joues.', 25),
('Epée', 'Plus la puissance électrique de Pikachu est élevée, plus les poches de ses joues sont extensibles.', 25),
('Bouclier', 'Les Pikachu se disent bonjour en se frottant la queue et en y faisant passer du courant électrique.', 25),
('Légendes Pokémon : Arceus', 'Cet astucieux Pokémon gîte en forêt. Ses bajoues contiennent des poches qui emmagasinent l`électricité dont il se sert pour griller les Baies avant de s`en repaître.', 25),
('Diamant Etincelant', 'Il vit en forêts avec ses pairs. Les poches sur ses joues emmagasinent de l`électricité.', 25),
('Perle Scintillante', 'Les poches électriques sur ses joues crépitent lorsqu`il est sur ses gardes.', 25),
('Ecarlate', 'Quand il s`énerve, il libère instantanément l`énergie emmagasinée dans les poches de ses joues.', 25),
('Violet', 'Quand plusieurs de ces Pokémon se réunissent, ils provoquent de gigantesques orages.', 25),
('Rouge', 'Ses oreilles se dressent lorsque les poches d`électricité sur ses joues sont chargées.', 26),
('Bleu', 'Il se protège des décharges grâce à sa queue, qui dissipe l`électricité dans le sol.', 26),
('Epée', 'Sa longue queue agit comme une prise de terre qui l`empêche d`être affecté par le courant à haute tension accumulé dans son corps.', 26),
('Bouclier', 'Si ses joues sont à court d`énergie, il lève la queue et capte l`électricité contenue dans l`atmosphère.', 26),
('Diamant Etincelant', 'Il devient agressif lorsque son corps emmagasine trop d`électricité. Il laisse alors cette électricité s`échapper par sa queue.', 26),
('Perle Scintillante', 'Il envoie des décharges de 100 000 volts, ce qui lui permet de mettre au tapis des ennemis bien plus imposants que lui en une seule attaque.', 26),
('Légendes Pokémon : Arceus', 'Ses décharges électrique outrepassent les 100 000 volts. Une seules d`entre elles suffirait à assommer un Pachyradjah, un Pokémon de ma région natale.', 26),
('Ecarlate', 'Il se protège des décharges grâce à sa queue, qui dissipe l`électricité dans le sol.', 26),
('Violet', 'Ses oreilles se dressent lorsque les poches d`électricité sur ses joues sont chargées.', 26);